name: Package addon

on:
  push:
    branches:
      - main

    tags:
      - '*'

    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Run luacheck
      #   uses: BigWigsMods/actions/luacheck@master
      #   with:
      #     args: -q

      - name: WoW Packager
        uses: BigWigsMods/packager@master
        with:
          args: |
            -g retail
            -g classic
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
